project:
  type: website
editor: source

#Website
website:
  favicon: /images/game_of_life.png
  page-navigation: true
  title: "M-Gemmell"
  description: "Main website for M-Gemmell's various github based websites"
##Navbar
  navbar:
    title: M-Gemmell
    logo: "images/game_of_life_2.png"
    collapse-below: lg
###Navbar left
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Education"
        href: education.qmd
      - text: "Academia"
        href: academia.qmd
      - text: "Hobbies"
        href: hobbies.qmd
      - text: "Guides"
        href: guides.qmd
###Navbar right
    right:
    # List of icons: https://icons.getbootstrap.com/
      - icon: cup
        href: https://ko-fi.com/waveofinspiration
        aria-label: Ko-fi
      - icon: github
        href: https://github.com/m-gemmell/
        aria-label: GitHub
      - text: "![](/images/Bluesky_Logo.svg){height=20px}"
        href: https://bsky.app/profile/m-gemmell.bsky.social
##Apge footer
  page-footer:
    center: |
      [![ko-fi](https://ko-fi.com/img/githubbutton_sm.svg)](https://ko-fi.com/K3K6IRLA0)
##Sidebar
  sidebar:
    - id: Overview
      title: "Overview"
      style: "floating"
      align: left
      contents:
        - href: index.qmd
    - id: Education
      title: "Education"
      style: "floating"
      align: left
      contents:
        - href: education.qmd
    - id: Academia
      title: "Academia"
      style: "floating"
      align: left
      contents:
        - href: academia.qmd
    - id: Hobbies
      title: "Hobbies"
      style: "floating"
      align: left
      contents:
        - href: hobbies.qmd
    - id: Guides
      title: "Guides"
      style: "floating"
      align: left
      contents:
        - href: guides.qmd


#Format
format:
  html:
    grid:
      sidebar-width: 200px
      body-width: 1000px
      margin-width: 200px
      gutter-width: 0.75em
    #HTML themes: https://quarto.org/docs/output-formats/html-themes.html
    theme: 
      dark: [darkly, styles.scss]
      light: [cosmo, styles.scss]
    mainfont: Lexend
    toc: true